environment:
  - PORT=3000
services:
  web:
    domain: ${HOST}
    build: .
    port: 3000
    ports:
      - 3001
balancers:
  ingress:
    annotations:
    - test.annotation.org/foo=bar
    service: web
    ports:
      5000:
        protocol: UDP
        port: 3000
