environment:
  - PORT=3000
resources:
  cache:
    type: redis
    options:
      version: 6
  db:
    type: postgres
    options:
      version: 13
  db2:
    type: postgres
    image: pgvector/pgvector:pg16
    options:
      version: 13
  memcached:
    type: memcached
    options:
      version: 1.6
services:
  web:
    domain: ${HOST}
    build: .
    port: 3000
    ports:
      - 3001/tcp
