environment:
  - PORT=3000
resources:
  database:
    type: postgres
	options:
	  storage: 10
  queue:
    type: redis
services:
  web:
    domain: ${HOST}
    build: .
    port: 3000
    ports:
      - 3001/udp
balancers:
  ingress:
    annotations:
    - test.annotation.org/foo=bar
    service: web
    ports:
      5000: 3000
