environment:
  - NODE_ENV=production
  - PORT=3000
services:
  web:
    build: .
    command: node app.js
    port: 3000
    scale:
      count: 1
      cpu: 128
      memory: 256
    resources:
      - cache
      - db
      - memcached
    ingressAnnotations:
      - nginx.ingress.kubernetes.io/limit-rpm=10
      - nginx.ingress.kubernetes.io/enable-access-log=false
    liveness:
      path: /liveness/check
      grace: 15
      interval: 5
      timeout: 3
      successThreshold: 1
      failureThreshold: 3
    balancers:
      ingress:
        annotations:
        - service.beta.kubernetes.io/aws-load-balancer-scheme=internal
        - service.beta.kubernetes.io/aws-load-balancer-internal=true
        - service.beta.kubernetes.io/aws-load-balancer-type=nlb
        - service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags=Service=web
        service: web
        ports:
          80: 3000

resources:
  cache:
    type: redis
    image: circleci/redis:7.0-rc-alpine
    options:
      version: 6
  db:
    type: postgres
    options:
      version: 16
  memcached:
    type: memcached
    image: bitnami/memcached:latest
    options:
      version: 1.6
  mysql:
    type: mysql
    image: bitnami/mysql:8.0.39
  postgis:
    type: postgis
    image: circleci/postgres:9-stretch-postgis-ram
  mariadb:
    type: mariadb
    image: circleci/mariadb:10.2-ram
